// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEmIRxeXTljZlkdfRK_-6IBcKUDdylNR8',
    appId: '1:522767502086:web:3561e0cf7afa80c2026c87',
    messagingSenderId: '522767502086',
    projectId: 'chat-app-dac6c',
    authDomain: 'chat-app-dac6c.firebaseapp.com',
    storageBucket: 'chat-app-dac6c.appspot.com',
    measurementId: 'G-81BF85W4SY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7TyQz-PxXNd_REOHiXt4CdJKIPsbSXok',
    appId: '1:522767502086:android:91847a7703e5965f026c87',
    messagingSenderId: '522767502086',
    projectId: 'chat-app-dac6c',
    storageBucket: 'chat-app-dac6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL_aDjOdHyX6boGWM-r-oVguFH0--xAoM',
    appId: '1:522767502086:ios:421082ee6921779e026c87',
    messagingSenderId: '522767502086',
    projectId: 'chat-app-dac6c',
    storageBucket: 'chat-app-dac6c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL_aDjOdHyX6boGWM-r-oVguFH0--xAoM',
    appId: '1:522767502086:ios:421082ee6921779e026c87',
    messagingSenderId: '522767502086',
    projectId: 'chat-app-dac6c',
    storageBucket: 'chat-app-dac6c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
